### ISSUE TITLE
No comments for variables in subroutines

### ISSUE THREAD

**Issue by laurarnichols** [Fortran-FOSS-Programmers/ford#285]
I'm not sure if I'm missing something or if this is expected behavior, but it seems like comments on variables that are internal to subroutines or functions are completely ignored. 

As an example, I am working through some code I am trying to update and have the following subroutine:
```fortran
  subroutine readInput()
    !! Delete any previous output, initialize input variables,
    !! start a timer, and read in the input files
    !!
    !! @todo
    !! Change this subroutine to have arguments to make clear
    !! that these variables are getting changed
    !! @endtodo
    !!
    implicit none
    !
    logical :: file_exists
      !! Whether or not the output file already exists
      !! @todo
      !! Change `file_exists` to `fileExists`
      !! @endtodo
    !
    ...
```

I can see the first Todo block rendered, but I don't see the comment or Todo under the variable declaration. Is there something I am doing wrong here or is this expected behavior?

**Comment by cmacmackin** [comment]
This is the default behaviour in FORD (although I see that the documentation contained an error and claimed otherwise--I've fixed that now). You can change it by setting "[proc_internals](https://github.com/Fortran-FOSS-Programmers/ford/wiki/Project-File-Options#proc_internals): true" in the project file.

**Comment by laurarnichols** [comment]
That worked! Thanks!
