### ISSUE TITLE
Source files visible after setting `source: false`

### ISSUE THREAD

**Issue by lizzyd710** [Fortran-FOSS-Programmers/ford#428]
I'm documenting a project that needs the source code to be hidden from documentation pages, but I'm still able to view the source code from the documentation pages and it still generates files in `./doc/src/`. Is there something else I have to do besides set that option in the project file?

Using version 6.1.12.

**Comment by lizzyd710** [comment]
I realize I may have misunderstood what that option does. I thought it would hide the source code everywhere in the documentation, as in source files not being included at all.

**Comment by ZedThree** [comment]
Hi @lizzyd710, I'm afraid I'm not sure when I'll get time to look into this properly, but here's some pointers that might help. I recommend trying out [`breakpoint()`](https://docs.python.org/3/library/functions.html?highlight=breakpoint#breakpoint) to jump into `ford` and see what's going on.

It looks like `incl_src` doesn't need any special handling when parsing the arguments, so there's no specific code to handle it in `__init__.py`. This bit makes sure it's a `bool`:

https://github.com/Fortran-FOSS-Programmers/ford/blob/391a3ac4a74da66719a48a15c3678c92f81924ed/ford/__init__.py#L416-L432

After that bit, `proj_data["incl_src"]` should be either `True` or `False`, depending on your input options.

The default value for `incl_src` is set at L165 in that file.

Here's where we copy the source files into `./doc/src`:

https://github.com/Fortran-FOSS-Programmers/ford/blob/391a3ac4a74da66719a48a15c3678c92f81924ed/ford/output.py#L238-L240

Lastly, I've just looked at the HTML templates, I think at least part of the problem is there:

https://github.com/Fortran-FOSS-Programmers/ford/blob/391a3ac4a74da66719a48a15c3678c92f81924ed/ford/templates/file_page.html#L12

I think it should be `src.incl_src` here. If you look at the other templates that use `incl_src`, I think they all need different qualified names, as it's getting passed in as an attribute of an object, rather than as data by itself.

**Comment by lizzyd710** [comment]
I saw that someone submitted a PR (#316) to address this a while ago so maybe something got changed later which unintentionally broke that feature. Thanks for giving me some clues on where to look--I'll see if I can figure out what happened and make a PR.

**Comment by lizzyd710** [comment]
Okay so I figured out what's going on. `source` and `incl_src` are two different things. The wiki says that setting `source: false` will hide the source code, which is technically true, but it only hides the source code for individual pages such as modules, subroutines, etc. It doesn't hide the source code completely, because you can still access "Source Files" from the menu bar. To disable this, you have to use a completely different option in the project file, `incl_src`. I'm not sure if this is intentional behavior or not but if so, I think the wiki should be updated to clarify the distinction.

**Comment by ZedThree** [comment]
Oh dear, that's a bit confusing, sorry about that! We do really need to sort out our docs, somewhat ironically.

If you have chance, please could you update the wiki?

**Comment by lizzyd710** [comment]
Sure, no problem! Thanks for helping me out!
