### ISSUE TITLE
RuntimeError: 'str object' has no attribute 'meta'

### ISSUE THREAD

**Issue by JulesKouatchou** [Fortran-FOSS-Programmers/ford#522]
Hi,

I am getting an error message while trying to create the HTML documentation:

   RuntimeError: .... 'str object' has no attribute 'meta'

I am wondering if you could let me know if I am doing something wrong. Here is a link to a simple reproducer:

https://drive.google.com/file/d/1blRHbtvetO0zQGkQaZtz_mEtQQyUjOoU/view?usp=sharing

The Fortran source code is in the folder `geom` and the folder `Ford` contains the Ford project file.

Thank you for your asistance.

Cheers,

Jules

**Comment by ZedThree** [comment]
Hi @JulesKouatchou, I think this is most likely due to the line

```fortran
      procedure, deferred :: get_esmf_geom
```

in `MaplGeom.F90`. `deferred` procedures need an interface, something like:

```fortran
      procedure(esmf_geom_interface), deferred :: get_esmf_geom
```

where `esmf_geom_interface` is some `abstract interface`.

Ideally ford would catch this sooner with a more helpful error message. I will try and fix that at some point!

**Comment by JulesKouatchou** [comment]
Thank you for working on the issue and the information you provided.
