### ISSUE TITLE
Upgrade bundled javascript files

### ISSUE THREAD

**Issue by bkmgit** [Fortran-FOSS-Programmers/ford#586]
Use newer versions of [jquery](https://github.com/jquery/jquery) for https://github.com/Fortran-FOSS-Programmers/ford/blob/master/ford/js/jquery-2.1.3.min.js
and [svg-pan-zoom](https://github.com/bumbu/svg-pan-zoom) for https://github.com/Fortran-FOSS-Programmers/ford/blob/master/ford/js/svg-pan-zoom.min.js

**Comment by ZedThree** [comment]
Ah, I meant to delete the bundled jquery, we're now using it from a CDN (see [base.html](https://github.com/Fortran-FOSS-Programmers/ford/blob/cd71a3f924277c2cc6562a6533959481182721b7/ford/templates/base.html#L29) template).

Looks like svg-pan-zoom has had some bug fixes, but hasn't been updated since 2019. Any suggestions for replacements welcome!
